# Generated by Django 4.0.5 on 2022-06-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart_all_functionalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_entry',
            name='worked_time',
            field=models.TimeField(blank=True),
        ),
    ]
