# Generated by Django 4.0.5 on 2022-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart_all_functionalities', '0003_alter_user_entry_worked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_entry',
            name='worked_time',
            field=models.TimeField(blank=True, default=0),
        ),
    ]
