# Generated by Django 4.0.5 on 2022-06-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart_all_functionalities', '0005_alter_user_entry_worked_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_entry',
            name='worked_time',
        ),
    ]
