# Generated by Django 4.0.5 on 2022-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart_all_functionalities', '0011_alter_user_settings_user_worked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_settings',
            name='annual_billing_target_in_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='user_worked_time',
            field=models.FloatField(default=0.0),
        ),
    ]
