# Generated by Django 4.0.5 on 2022-07-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart_all_functionalities', '0012_alter_user_settings_annual_billing_target_in_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_settings',
            name='annual_billing_target_in_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='annual_time_in_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='fiscal_year_start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
    ]
