# Generated by Django 4.0.5 on 2022-07-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart_all_functionalities', '0013_alter_user_settings_annual_billing_target_in_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_settings',
            name='fiscal_year_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
